In [1]:
#numpy demo
import numpy as np

In [3]:
#创建ndarray  array 函数接受一切序列格式(包含一个numpy数组) 转换成numpy数组

data=[7,6.5,10,123]

arr1=np.array(data)
#等长多列表组合成多维数组

data2=([1,2,3],[4,5,6])
arr2=np.array(data2)
#arr2
#arr2.shape  维度
#arr2.dtype  类型

In [4]:
#其他新建数组的方式和技巧
np.zeros(10)
np.zeros((3,5))
np.empty((2,4,2))

array([[[  0.00000000e+000,   0.00000000e+000],
        [  2.12215770e-314,   1.97626258e-323],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,  -4.60750798e-126]],

       [[  0.00000000e+000,   0.00000000e+000],
        [ -3.02611129e+205,   0.00000000e+000],
        [  0.00000000e+000,   1.28019457e-271],
        [  2.15122387e-314,   2.16195671e-314]]])

In [23]:
#ndarray 数值类型
a=np.array([1,2,3],dtype='float64')
b=np.array([1.1,12,3,4],dtype='int32')
#a.dtype
b.dtype
#精度已丢失
c=b.astype('float64')
c.dtype

dtype('float64')

In [29]:
uint1=np.array([123123123,534534534,23434654,54645454],dtype='u4')
uint1

array([123123123, 534534534,  23434654,  54645454], dtype=uint32)

In [30]:
int1=np.array([123123123,53453453,23334654,54645454],dtype='i4')
int1

array([123123123,  53453453,  23334654,  54645454], dtype=int32)

In [43]:
#索引和切片
arr3=np.arange(10)
arr3[5:8]
#数组的切片是个视图，不是copy所以更改会反映到源数组上
view_arr=arr3[5:8]
view_arr[1]=123
#arr3
#要得到一个copy需要arr3[5:8].copy
view_arr2=arr3[5:8].copy()
view_arr2[:] = 12
arr3

array([  0,   1,   2,   3,   4,   5, 123,   7,   8,   9])

In [8]:
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])
arr4.shape

(2, 2, 3)

In [12]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d.shape
arr2d[2]
arr2d[2][1]
#逗号分隔索引
arr2d[2,1]

8